service: datasource-api

frameworkVersion: '3'

provider:
    name: aws
    region: ap-northeast-2
    stage: dev
    ecr:
        images:
            appimage:
                path: ./

functions:
    main:
        image:
            name: appimage
            command:
                - pwd
            entryPoint:
                - '/lambda-entrypoint.sh'
        events:
            - http:
                  method: any
                  path: /{any+}
